name: ðŸš€ Deploy Hyperfocus Constellation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ Checkout code
      uses: actions/checkout@v3

    - name: ðŸ”§ Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: ðŸ“¦ Install dependencies
      run: npm ci

    - name: ðŸ§ª Run tests
      run: npm test

    - name: â™¿ Accessibility test
      run: npm run test:accessibility

    - name: ðŸ” Lint code
      run: npm run lint

    - name: ðŸ—ï¸ Build project
      run: npm run build

    - name: ðŸš€ Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src
        commit_message: 'ðŸŒŸ Deploy constellation update'

  accessibility-audit:
    runs-on: ubuntu-latest
    name: â™¿ Accessibility Audit

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: ðŸ” Run accessibility audit
      run: |
        npm install -g @axe-core/cli
        axe src/index.html --exit

    - name: ðŸ“Š Generate accessibility report
      run: |
        axe src/index.html --reporter html > accessibility-report.html

    - name: ðŸ“¤ Upload accessibility report
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-report
        path: accessibility-report.html
